### ISSUE TITLE
allow weather-lock to set thunder as per vanilla minecraft weather options

### ISSUE THREAD

**Issue by DalBrar** [EngineHub/WorldGuard#1645]
**Is your feature request related to a problem? Please describe.**
Currently weather-lock only permits "rain" or "clear" but the vanilla weather command allows "rain, clear, thunder". Please add thunder to weather-lock.

**Describe the solution you'd like**
weather-lock: thunder

**Describe alternatives you've considered**
Checked if worldguard extra flags had the feature but it does not.

**Additional context**
Just in time for halloween. Would be a nice feature to have where certain regions are ominous n stormy.

**Comment by JOO200** [comment]
Use "thunder_storm" to set your weather lock flag to thunder.

**Comment by DalBrar** [comment]
Ah perfect, thank you. The flags page ([click here](https://worldguard.enginehub.org/en/latest/regions/flags/)) does not state any thunder option. It may require an update.

**Comment by DalBrar** [comment]
I just switched a region to "thunder_storm" and it appears to be no different than the "rain" option. No thunder is being heard. Have tried exiting and re-entering the region

**Comment by wizjany** [comment]
i think it's intentionally left out because despite being in the weather registry, bukkit only allows setting the rainy state or clear state in the api. while there are nowadays some additional packets that control sky color/thunderyness or something, bukkit doesn't seem to expose any of that. additionally, lightning entities are a completely different matter as well and aren't covered by the game state change. If someone wants to find a way to add this to bukkit api, I'll reopen on our end, in the meantime this isn't feasible from WG.
