### ISSUE TITLE
block-armor-stand-destroy: true setting NOT working with fireworks

### ISSUE THREAD

**Issue by SmokeY1337** [EngineHub/WorldGuard#1667]
**Versions**

WorldEdit version:
_WorldEdit 7.2.0_

WorldGuard version:
_WorldGuard 7.0.4_

Platform version:
_git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)_

**Describe the bug**
_block-armor-stand-destroy: true_ is NOT working with firework explosions. In a result the armor stand is destroyed by the firework.

**Expected behavior**
With this setting set to TRUE armor stands should NOT be destroyed when player is using fireworks, that have certain explosion effect, as in previous versions of WorldGuard.

**Additional context**
When using fireworks, that have certain explosion effect, a player is still able to destroy armor stands, despite the setting block-armor-stand-destroy: true. This happens when the player lands or passes near them at the same time when the firework explosion happens. The setting was working properly on previous versions of WorldGuard such as 7.0.3 & bellow.

**NOTE:** I don't know if the issue is only with fireworks, this has NOT been tested with other things.

**Comment by wizjany** [comment]
this is correct. as the setting indicates, it is only supposed to prevent mobs from destroying armor stands. previously, spigot did not have the source entity attached to fireworks (in fact fireworks weren't even considered projectiles). since this has now changed, the setting works as originally intended.
