### ISSUE TITLE
teleport-on-void-falling doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [EngineHub/WorldGuard#1696]
**Versions**
WorldEdit version: 1.16-492
WorldGuard version: WorldGuard version 7.0.5-SNAPSHOT+15a0809
Platform version: git-Tuinity-"cc34294"

**Describe the bug**
Players fall down infinitely in the void of the end.

**To Reproduce**
1. Set the following config options in the player-damage section, as listed below:
```
    disable-void-damage: false
    teleport-on-void-falling: true
    reset-fall-on-void-teleport: false
```
2. Enter the end.
3. Jump into the void.

**Expected behavior**
Players should be teleported onto a glass block when falling into the void.

**Additional context**
https://paste.enginehub.org/tBp4pL59l.report
WorldGuardExtraFlags version 4.1.5-SNAPSHOT

**Comment by wizjany** [comment]
Your described expected behavior doesn't match up to the intended actual behavior, so I'm going to assume you just don't understand how the feature works. Specifically, there's no glass block at play - it's only supposed to teleport you directly up to existing land, e.g. for cases when you clip through the world when teleporting (which is much less common these days than previously).
