### ISSUE TITLE
Armor stand interaction default blocked with no proper flag.

### ISSUE THREAD

**Issue by MithrandirCraft** [EngineHub/WorldGuard#1861]
### The Problem

There isn't a flag for allowing or disallowing player interaction with an armorstand.

### A Solution

Decouple this feature from the basic protection, and add the specific flag. 

### Anything Else?

It's really annoying that you can't flag this. People get messages when interacting with my invisible armor stand, which acts as a diegetic UI made with MythicMobs.
![imagen](https://user-images.githubusercontent.com/6623704/145716848-8ef01ffe-232b-4113-82a9-c652b4817d3f.png)

This isn't the actual armorstand UI I mention, just a clear view of the message you will always get (unconfigurable) when interacting with armorstands.

**Comment by wizjany** [comment]
there are two possible solutions here:

1) plugins that require interaction with armor stands be treated as non-modifying need to listen on a lower priority and cancel the event
2) bukkit gets proper events for modification of armor stands so that plugins can properly separate the "interaction" and "modification" of armor stands.

unprotecting armor stands is *not* a solution. we can't allow "interaction but not modification" of armor stands without (2).
