### ISSUE TITLE
Plugin maven build fails when using worldguard-bukkit 7.0.6 as dependency in pom

### ISSUE THREAD

**Issue by mirolm** [EngineHub/WorldGuard#1874]
### WorldEdit Version

7.2.8

### WorldGuard Version

7.0.6

### Platform Version

git-Paper-408 (MC: 1.17.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I'm trying to build a plugin which uses worldguard-bukkit 7.0.6 in it's pom.xml. It all worked out without issues for weeks, until several days ago build started to fail with the following error:

````
[WARNING] The POM for com.sk89q.worldedit:worldedit-core:jar:7.2.6-SNAPSHOT is missing, no dependency information available
````

````
[ERROR] Failed to execute goal on project zPermissions: Could not resolve dependencies for project org.tyrannyofheaven.bukkit:zPermissions:jar:1.4.5-SNAPSHOT: com.sk89q.worldedit:worldedit-core:jar:7.2.6-SNAPSHOT was not found in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]
````

I have the repository as follows:

````
        <repository>
            <id>sk89q-repo</id>
            <url>https://maven.sk89q.com/repo/</url>
        </repository>
````

I digged a little in https://maven.sk89q.com/repo/ and found that there is no maven-metadata.xml into 7.2.6-SNAPSHOT folder. 

Could this cause the issue with the build?

### Expected Behavior

Build should work without issues.

### Reproduction Steps

1. Delete the .m2 folder to clean maven cache.
2. Start the build of the plugin with maven.
3. Build fails with the mentioned above error.

**Comment by JOO200** [comment]
The maven sk89q repo is not updated anymore:

The Maven repository for all our projects has been migrated to a new server, for long-term stability.

Due to this change, the previously deprecated legacy repository URL maven.sk89q.com is NO LONGER UPDATED. Please migrate to using https://maven.enginehub.org/repo/ ASAP, as new releases will ONLY be seen there.

Additionally, many proxied repos have been removed. Please use the appropriate repository to pull your artifacts.

Please let us know if anything that was using https://maven.enginehub.org/ prior to this change, and does not fall under the above exceptions, breaks.
