### ISSUE TITLE
Mob spawn adjustments in time-lock to suit the time stated within the lock

### ISSUE THREAD

**Issue by Jqnnies** [EngineHub/WorldGuard#1936]
### The Problem

I've been trying to test out time zones with regions, and one thing that bothers me is the inconsistency of mob spawning since they follow the global format of spawning as time-lock is client sided.

### A Solution

Have it so mobs can be overridden to spawn based on the time-lock set time, that way you can have a place thats constantly night that spawns mobs, or proper time zones when making an SMP map.

**Comment by wizjany** [comment]
this is infeasible on a general case since time lock is purely client-sided and players in the same place could see different times based on region groups or whatever else.
maybe some paper-specific plugin could discount players whose local time is day from mob-spawning, but i think that's out of scope for worldguard.
