### ISSUE TITLE
Lava/Watter Bucket

### ISSUE THREAD

**Issue by dayd21git** [EngineHub/WorldGuard#2030]
### The Problem

I can't get water or lava from the region by clicking an empty bucket.
I use the interact:allow and use:allow flags.
Region: watertower(screenshot)
WG version: `7.0.5+3827266`

### A Solution

I have to get a bucket of liquid when clicking on the liquid with an empty bucket.

### Alternatives

Unknown

### Anything Else?

![06 08 2023-01](https://github.com/EngineHub/WorldGuard/assets/61166549/df84484e-1bea-430c-8e43-5ce2074d0e0d)

**Comment by me4502** [comment]
Don't erase the issue template. You're using a very old & unsupported version, and your screenshots indicate you're doing multiple things that are fairly broken and covered by the issue template.

If you have to erase the issue template to make an issue, you're using an unsupported environment and the cause of the issue is almost always the environment.
